
# This file is automatically generated, you probably don't want to edit this

quickpsyfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quickpsyfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            k = NULL,
            x = NULL,
            n = NULL,
            group = NULL,
            fun = "cum_normal_fun",
            guess = 0,
            lapses = 0,
            plotcurve = FALSE,
            log = FALSE, ...) {

            super$initialize(
                package="jmvquickpsy",
                name="quickpsyfit",
                requiresData=TRUE,
                ...)

            private$..k <- jmvcore::OptionVariable$new(
                "k",
                k,
                permitted=list(
                    "numeric"))
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                permitted=list(
                    "numeric"))
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n,
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group)
            private$..fun <- jmvcore::OptionList$new(
                "fun",
                fun,
                options=list(
                    "cum_normal_fun",
                    "logistic_fun",
                    "weibull_fun"),
                default="cum_normal_fun")
            private$..guess <- jmvcore::OptionNumber$new(
                "guess",
                guess,
                default=0)
            private$..lapses <- jmvcore::OptionNumber$new(
                "lapses",
                lapses,
                default=0)
            private$..plotcurve <- jmvcore::OptionBool$new(
                "plotcurve",
                plotcurve,
                default=FALSE)
            private$..log <- jmvcore::OptionBool$new(
                "log",
                log,
                default=FALSE)

            self$.addOption(private$..k)
            self$.addOption(private$..x)
            self$.addOption(private$..n)
            self$.addOption(private$..group)
            self$.addOption(private$..fun)
            self$.addOption(private$..guess)
            self$.addOption(private$..lapses)
            self$.addOption(private$..plotcurve)
            self$.addOption(private$..log)
        }),
    active = list(
        k = function() private$..k$value,
        x = function() private$..x$value,
        n = function() private$..n$value,
        group = function() private$..group$value,
        fun = function() private$..fun$value,
        guess = function() private$..guess$value,
        lapses = function() private$..lapses$value,
        plotcurve = function() private$..plotcurve$value,
        log = function() private$..log$value),
    private = list(
        ..k = NA,
        ..x = NA,
        ..n = NA,
        ..group = NA,
        ..fun = NA,
        ..guess = NA,
        ..lapses = NA,
        ..plotcurve = NA,
        ..log = NA)
)

quickpsyfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quickpsyfitResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        params = function() private$.items[["params"]],
        threshold = function() private$.items[["threshold"]],
        plotcurve = function() private$.items[["plotcurve"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fit Psychometric Function")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Fit Psychometric Function"))
            self$add(jmvcore::Table$new(
                options=options,
                name="params",
                title="Fitted parameters",
                columns=list(
                    list(
                        `name`="cond", 
                        `type`="text", 
                        `title`="Condition"),
                    list(
                        `name`="par", 
                        `type`="text", 
                        `title`="Parameter"),
                    list(
                        `name`="value", 
                        `type`="number", 
                        `title`="Estimate"),
                    list(
                        `name`="low", 
                        `type`="number", 
                        `title`="Low"),
                    list(
                        `name`="high", 
                        `type`="number", 
                        `title`="High"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="threshold",
                title="Threshold estimates",
                columns=list(
                    list(
                        `name`="cond", 
                        `type`="text", 
                        `title`="Condition"),
                    list(
                        `name`="prob", 
                        `type`="number", 
                        `title`="Probability"),
                    list(
                        `name`="value", 
                        `type`="number", 
                        `title`="Estimate"),
                    list(
                        `name`="low", 
                        `type`="number", 
                        `title`="Low"),
                    list(
                        `name`="high", 
                        `type`="number", 
                        `title`="High"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotcurve",
                title="Fitted psychometric curve",
                width=400,
                height=300,
                renderFun=".plotCurve"))}))

quickpsyfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quickpsyfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvquickpsy",
                name = "quickpsyfit",
                version = c(1,0,0),
                options = options,
                results = quickpsyfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Fit Psychometric Function
#'
#' 
#' @param data .
#' @param k .
#' @param x .
#' @param n .
#' @param group .
#' @param fun .
#' @param guess .
#' @param lapses .
#' @param plotcurve .
#' @param log .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$params} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$threshold} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotcurve} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$params$asDF}
#'
#' \code{as.data.frame(results$params)}
#'
#' @export
quickpsyfit <- function(
    data,
    k,
    x,
    n,
    group,
    fun = "cum_normal_fun",
    guess = 0,
    lapses = 0,
    plotcurve = FALSE,
    log = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("quickpsyfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(k)) k <- jmvcore::resolveQuo(jmvcore::enquo(k))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(n)) n <- jmvcore::resolveQuo(jmvcore::enquo(n))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(k), k, NULL),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(n), n, NULL),
            `if`( ! missing(group), group, NULL))


    options <- quickpsyfitOptions$new(
        k = k,
        x = x,
        n = n,
        group = group,
        fun = fun,
        guess = guess,
        lapses = lapses,
        plotcurve = plotcurve,
        log = log)

    analysis <- quickpsyfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

